The TMU CAN now report its temp
RIT-EVT/TMU pull request #2
Opened 2023-02-24 00:18 UTC by ActuallyZach

Added the ability for the TMU too send its temperature data over CAN

2023-02-24 00:21 UTC, ActuallyZach commented
![](https://github.trello.services/images/mini-trello-icon.png) [TMU CANopen Setup](https://trello.com/c/22Fp63k4/126-tmu-canopen-setup)

2023-02-24 00:54 UTC, mjmagee991 requested changes
A couple formatting issues and one platform problem

2023-02-24 00:54 UTC, mjmagee991 commented on include/TMU.hpp
> +            .Data = (uintptr_t) 5},
```suggestion
            .Data = (uintptr_t) 5,},
```
If you have a comma here in each element in the list, the autoformatter is much happier

2023-02-24 00:54 UTC, mjmagee991 commented on src/TMU.cpp
> +}
```suggestion
}

```

2023-02-24 00:54 UTC, mjmagee991 commented on targets/DEV1-TMU/CMakeLists.txt
> +project(TMUmain)
```suggestion
project(DEV1-TMU)
```

2023-02-24 00:54 UTC, mjmagee991 commented on targets/DEV1-TMU/CMakeLists.txt
> +
```suggestion
```

2023-02-24 00:54 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +    DEV::Timerf302x8 timer(TIM2, 100);
Update the EVT-core submodule and make this platform agnostic

2023-02-24 00:54 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +    TMU::TMU tmu{};
```suggestion
    TMU::TMU tmu;
```

2023-02-24 01:38 UTC, ishan-renjen approved these changes

2023-02-24 01:49 UTC, mjmagee991 requested changes
One minor detail

2023-02-24 01:49 UTC, mjmagee991 commented on src/TMU.cpp
> +    return &objectDictionary[0];
```suggestion
    return objectDictionary;
```

2023-02-25 01:25 UTC, mjmagee991 approved these changes
Nice work

2023-02-25 14:58 UTC, merged