MAX Temp Reading
RIT-EVT/TMU pull request #3
Opened 2023-02-24 00:47 UTC by bencerr

Driver code for the the MAX31855, reads the temperature with two decimal places in celsius.

2023-02-24 01:40 UTC, mjmagee991 requested changes
A couple minor issues

2023-02-24 01:40 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +#include "EVT/io/SPI.hpp"
Use `<>` instead of `""`

2023-02-24 01:40 UTC, mjmagee991 commented on src/dev/MAX31855.cpp
> +    spi.startTransmission(0);
The device number should be stored in the class, not hardcoded to 0

2023-02-24 01:40 UTC, mjmagee991 commented on targets/MAX31855/main.cpp
> +#include "EVT/utils/time.hpp"
Use `<>` instead of `""`

2023-02-24 01:40 UTC, mjmagee991 commented on targets/MAX31855/main.cpp
> +        ;
```suggestion
```

2023-02-24 01:47 UTC, ishan-renjen requested changes
line 2 of top level CMakeLists.txt should have the board name

2023-02-25 01:36 UTC, mjmagee991 requested changes
A couple more formatting issues

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +#endif//TMU_MAX31856_H
This should be moved to the end of the file, so the header guard works properly

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +using namespace EVT::core::IO;
```suggestion
using namespace EVT::core::IO;

```

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> + * Handles reading temp data from the MAX31855 ADC
Add a link to the datasheet

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +     * Returns the temp in celsius
This should return in centicelsius

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +    /** The device for SPI */
```suggestion
    /** The SPI device number for this device */
```
The variable name should probably be changed to match this comment and make its purpose a little clearer

2023-02-25 01:36 UTC, mjmagee991 commented on src/dev/MAX31855.cpp
> +    this->device = dev;
This can be done more safely in the initializer list instead of in the constructor body

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +    int16_t readTemp();
This should return a uint8_t. If we want to support negatives, we're going to have to change some of the bit shifting, but I don't think we're going to need to worry about that

2023-02-25 01:36 UTC, mjmagee991 commented on src/dev/MAX31855.cpp
> +    const int length = 4;
```suggestion
    const uint8_t length = 4;
```
Generally, we always want to specify the data length
You could also change this to a `#define` in the `.hpp` file to simplify the method a little

2023-02-25 01:36 UTC, mjmagee991 commented on src/dev/MAX31855.cpp
> +    spi.startTransmission(this->device);
```suggestion
    spi.startTransmission(device);
```
This is just personal preference

2023-02-25 01:36 UTC, mjmagee991 commented on include/dev/MAX31855.h
> +#ifndef TMU_MAX31856_H
Rename this file to `MAX31855.hpp` to match the rest of our header files. Generally, we use `.h` with `.c` files, and `.hpp` with `.cpp` files, although `.h` works for both `.c` and `.cpp` files.

2023-02-25 01:36 UTC, mjmagee991 commented on src/dev/MAX31855.cpp
> +    return temp;
Add some blank lines in this method to make it easier to read

2023-02-25 14:47 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Thermocouple Driver](https://trello.com/c/htlGuE9P/37-thermocouple-driver)

2023-02-25 16:50 UTC, mjmagee991 approved these changes
Great job

2023-02-25 16:52 UTC, ActuallyZach approved these changes
Looks good

2023-02-25 16:55 UTC, merged