4 MAX SPI Devices
RIT-EVT/TMU pull request #5
Opened 2023-04-04 00:46 UTC by AarC10

2023-04-08 14:43 UTC, ActuallyTaylor approved these changes

2023-04-27 20:23 UTC, mjmagee991 requested changes
L⌀⌀p

2023-04-27 20:23 UTC, mjmagee991 commented on targets/MAX31855/main.cpp
> +        temp = MAX2.readTemp();
This implementation would be much cleaner with an array and a for loop.

2023-04-28 00:49 UTC, ishan-renjen approved these changes

2023-04-28 07:29 UTC, mjmagee991 approved these changes

2023-04-28 07:33 UTC, merged