How many calorie
RIT-EVT/TMU pull request #7
Opened 2024-01-23 00:13 UTC by ol2764RIT

Added a python script for battery calorimetry testing. The script does the following

- Asks the user running the script for a specific COM port.
- Reads from the COM port into a new CSV file
- Logs The Temperature Array and the Error Array into the CSV File

2024-01-23 00:32 UTC, ol2764RIT commented
![](https://github.trello.services/images/mini-trello-icon.png) [Battery Calorimetry Test Support](https://trello.com/c/L8SlRzKi/189-battery-calorimetry-test-support)

2024-01-23 14:05 UTC, mjmagee991 requested changes
A couple minor changes. Also, make sure you back merge master before you try to merge because you have some changes missing

2024-01-23 14:05 UTC, mjmagee991 commented on CMakeLists.txt
> +add_library(${PROJECT_NAME} STATIC
Revert this change. CLion thinks it's smart, but it isn't

2024-01-23 14:05 UTC, mjmagee991 commented on targets/cal_test/cal_to_csv.py
> +com_port = input('Enter the COM port (Format: COMXX): ')
Technically, it's only formatted as `COMXX` on Windows. It's named differently on Mac and Linux, but those users should be able to figure it out for themselves

2024-01-23 14:05 UTC, mjmagee991 commented on targets/cal_test/cal_to_csv.py
> +    while True:
This while loop is going to cause the CSV file to be reopened and overwritten if a KeyboardInterrupt occurs. It doesn't look like you really need this here, but if you think you do, you can add something that checks if the file already exists and appends or starts a new file, so you don't accidentally delete all the data

2024-01-23 14:05 UTC, mjmagee991 commented on targets/cal_test/main.cpp
> +#include <EVT/io/UART.hpp>
Add a comment at the top explaining the purpose of the target

2024-01-23 14:05 UTC, mjmagee991 commented on targets/cal_test/cal_to_csv.py
Move this file to a new top-level folder called tools

2024-01-23 14:05 UTC, mjmagee991 commented on targets/cal_test/main.cpp
> +        uart.printf("temp1:%d, temp2:%d, temp3:%d, temp4:%d, error1:%d, error2:%d, error3:%d, error4:%d\r\n", temps[0], temps[1], temps[2], temps[3], errors[0], errors[1], errors[2], errors[3]);
For CSV files, we don't want the header in every line. We want `temp1, temp2, temp3, ...` once at the beginning of the file and then we just want the data, like `51, 42, 33, 41, ...`

2024-01-24 15:05 UTC, ol2764RIT commented
build is actively failing, just a skill issue I guess when back merging will fix.

2024-01-25 15:20 UTC, mjmagee991 commented
When you merged your CANopen upgrade branch into this branch, you brought over the updated submodule, which is breaking everything. Why did you merge that branch here?

2024-01-29 19:29 UTC, ol2764RIT commented
> When you merged your CANopen upgrade branch into this branch, you brought over the updated submodule, which is breaking everything. Why did you merge that branch here?

lowkey kinda misread when u said back merge and thought submodule update ¯\_(ツ)_/¯

2024-01-30 00:11 UTC, ActuallyTaylor requested changes

2024-01-30 00:11 UTC, ActuallyTaylor commented on targets/DEV1-TMU/main.cpp
>  extern "C" void COIfCanReceive(CO_IF_FRM* frm) {}
You should remove all of these these externs

2024-01-30 00:11 UTC, ActuallyTaylor commented on targets/cal_test/cal_to_csv.py
> +        csv_file_path = f'sensor_data.csv'
You don't need an fstring here

2024-02-03 15:26 UTC, ol2764RIT commented
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade TMU CANopen](https://trello.com/c/uQv4J4no/228-upgrade-tmu-canopen)

2024-02-03 16:02 UTC, mjmagee991 requested changes

2024-02-03 16:02 UTC, mjmagee991 commented on CMakeLists.txt
Revert your changes to this file

2024-02-03 16:02 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +#include "../../libs/EVT-core/samples/canopen/canopen_tpdo/TPDOCanNode.hpp"
Fix this include

2024-02-03 16:02 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +IO::UART& uart = IO::getUART<IO::Pin::UART_TX, IO::Pin::UART_RX>(9600);
Don't have a global uart

2024-02-03 16:02 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +//TPDO event handler to print the raw TPDO message when sending
Remove this

2024-02-03 16:02 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> +    //tpdo node
```suggestion
```

2024-02-08 22:59 UTC, mjmagee991 requested changes
Some things still haven't been resolved

2024-02-08 22:59 UTC, mjmagee991 commented on targets/DEV1-TMU/main.cpp
> -/**
Add this target explanation back in

2024-02-09 01:02 UTC, mjmagee991 approved these changes
Very epic and cool

2024-02-09 01:12 UTC, ActuallyTaylor approved these changes

2024-02-09 01:13 UTC, merged